### ISSUE TITLE
Create UI

### ISSUE THREAD

**Issue by ambhinav** [ambhinav/HabitChain#12]
- [x] View all Habits
- [x] Create Habits
- [x] Join Habits
- [x] Verify Habits (captcha & strava)
- [x] Integrate with **Web3** and Metamask

**Note from Prof**: UI does not have to be great -> if you UI is not out focus then add extra unit test cases to show the features work !
